#!/bin/bash

# This script will be located @ /data/home/copy_dir/geofile/tmp
# geofile-home is a clean home dir list from geofile-home
# geofile-home will be located @ /data/home/copy_dir/geofile/tmp
# movedatalog is the normal action log
# movedataerrorlog is the error log 

today=`/bin/date '+%Y_%m_%d_%H_%M_%S'`;
logfile="/data/home/copy_dir/geofile/tmp/movedatalog_$today"
/bin/touch $logfile
errorlogfile="/data/home/copy_dir/geofile/tmp/movedataerrorlog_$today"
/bin/touch $errorlogfile

function chk {
  if [ $? -ne 0 ] ; then
    /bin/echo "ERROR: $1"
#   exit 1
#   I do not want to exit. error in the log would be good enough.  
  fi
}

function move-to-geol-subdir {
if [ -d "/data/home/$1" ]
then
   if [ ! -d "/data/home/$1/geol" ]
   then
      if [ $1 == igm852 ]
      then
         /bin/mv /data/home/copy_dir/geofile/home/morozov/ /data/home/$1/geol/
         chk "can not move data for $1" >> $errorlogfile
      else
         /bin/mv /data/home/copy_dir/geofile/home/$1/ /data/home/$1/geol/
         chk "can not move data for $1" >> $errorlogfile
      fi 
      /bin/chown -Rh $1:posixusers /data/home/$1/geol
      chk "can not chown for $1" >> $errorlogfile
      /bin/echo "move data and change owner for $1" >> $logfile
   else
      /bin/echo "/data/home/$1/geol exists already" >> $errorlogfile
   fi
else
    /bin/echo "/data/home/$1 does not exist" >> $errorlogfile
fi
}

# fix permission
/bin/find /data/home/copy_dir/geofile/home -type d -print0 | /bin/xargs -0 chmod 700 
chk "can not fix permission for dir" >> $errorlogfile
/bin/find /data/home/copy_dir/geofile/home -type f -print0 | /bin/xargs -0 chmod go-rwx
chk "can not fix permission for file" >> $errorlogfile

while IFS= read -r THELINE; do
  if [ -n "$THELINE" ]; then
     if [ "$THELINE" == "morozov" ]
     then
        # nsid for morozov is igm852 
        move-to-geol-subdir igm852
     else
        # normal nsid
        move-to-geol-subdir $THELINE
     fi
fi
done < /data/home/copy_dir/geofile/tmp/geofile-home
